AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  AutoTagEC2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::172254782416:role/service-role/Auto_Tag_EC2-role-pmj9vrcp'
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - ec2.amazonaws.com
                eventName:
                  - CreateVolume
                  - RunInstances
                  - CreateImage
                  - CreateSnapshot
