 TagBasedEC2RestrictionsPolicy:
    Condition: CreateResources
    Properties:
      Description: >-
        This policy allows Start/Stop/Reboot/Terminate for EC2 instances where
        the tag 'Owner' doesn't match the current requester's user ID.
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: LaunchEC2Instances
            Effect: Allow
            Action:
              - 'ec2:Describe*'
              - 'ec2:RunInstances'
            Resource:
              - '*'
          - Sid: AllowActionsIfYouAreTheOwner
            Effect: Allow
            Action:
              - 'ec2:StopInstances'
              - 'ec2:StartInstances'
              - 'ec2:RebootInstances'
              - 'ec2:TerminateInstances'
            Condition:
              StringEquals:
                'ec2:ResourceTag/PrincipalId': '${aws:userid}'
            Resource:
              - '*'
      Groups:
        - !Ref ManageEC2InstancesGroup
    Type: 'AWS::IAM::ManagedPolicy'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5b191519-cd78-408c-8923-c55ca063fd1e
