Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: Function
      Runtime: python3.7
      Timeout: 300
      MemorySize: 128
